In [223]:
import pandas as pd

In [224]:
import numpy as np

In [225]:
import matplotlib.pyplot as plt

In [226]:
df = pd.read_csv("pollutionprocessed.csv")

In [227]:
df.head()

AQI.Value  AQI.Category  CO.AQI.Value  CO.AQI.Category  Ozone.AQI.Value  \
0         51             2             1                1               36   
1         41             1             1                1                5   
2         66             2             1                1               39   
3         34             1             1                1               34   
4         22             1             0                1               22   

   Ozone.AQI.Category  NO2.AQI.Value  NO2.AQI.Category  PM2.5.AQI.Value  \
0                   1              0                 1               51   
1                   1              1                 1               41   
2                   1              2                 1               66   
3                   1              0                 1               20   
4                   1              0                 1                6   

   PM2.5.AQI.Category  
0                   2  
1                   1  
2                   2  
3                   1  
4                   1

In [228]:
x = df.drop(["AQI.Value"], axis=1)
y = df["AQI.Value"]

In [229]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [230]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [231]:
linear.fit(x_train, y_train)

LinearRegression()

In [232]:
linear.score(x_test, y_test)

0.9805572617173257

# Classification

In [238]:
import pandas as pd

In [239]:
import numpy as np

In [240]:
import matplotlib.pyplot as plt 

In [241]:
df = pd.read_csv("heartprocessed.csv")

In [242]:
df.head()

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0             2  16.60        1                2       2               3   
1             2  20.34        2                2       1               0   
2             2  26.58        1                2       2              20   
3             2  24.21        2                2       2               0   
4             2  23.71        2                2       2              28   

   MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0            30            2    2            1     1         1   
1             0            2    2            2     1         2   
2            30            2    1            3     1         1   
3             0            2    2            4     1         2   
4             0            1    2            5     1         2   

   PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  SkinCancer  
0                 1          1          5       1              2           1  
1                 1          1          7       2              2           2  
2                 1          2          8       1              2           2  
3                 2          3          6       2              2           1  
4                 1          1          8       2              2           2

In [251]:
df[["HeartDisease"]].nunique()

HeartDisease    2
dtype: int64

In [254]:
df["HeartDisease"].value_counts()

2    292422
1     27373
Name: HeartDisease, dtype: int64

In [255]:
x = df.drop(["HeartDisease"], axis=1)
y = df["HeartDisease"]

In [259]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1, stratify=y)
from sklearn.model_selection import cross_val_score
knn_cv = KNeighborsClassifier(n_neighbors=3)
cv_scores = cross_val_score(knn_cv, x, y, cv=5)
print(cv_scores)
print(cv_scores.mean())

[0.89870073 0.89895089 0.89970137 0.89891962 0.89952939]
0.8991603996310136


In [268]:
from sklearn.metrics import confusion_matrix

In [271]:
knn_cv.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [272]:
y_pred = knn_cv.predict(x_test)

In [273]:
cm1 = confusion_matrix(y_pred, y_test)

In [274]:
print(cm1)

[[  832  2297]
 [ 7380 85430]]


In [260]:
from sklearn.tree import DecisionTreeClassifier

In [261]:
dtc_model = DecisionTreeClassifier(random_state=42)

In [262]:
dtc_model.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [263]:
dtc_model.score(x_test, y_test)

0.8604738427542501

In [275]:
y_pred=dtc_model.predict(x_test)

In [276]:
from sklearn.metrics import confusion_matrix

In [278]:
cm2 = confusion_matrix(y_test, y_pred)

In [279]:
print(cm2)

[[ 2069  6143]
 [ 7243 80484]]


In [280]:
from sklearn.metrics import accuracy_score, precision_score, f1_score

In [281]:
accuracy_score(y_test, y_pred)

0.8604738427542501

In [282]:
precision_score(y_test, y_pred)

0.22218642611683848

In [283]:
f1_score(y_test, y_pred)

0.23613330289888151